"""add product releases

Revision ID: 3b1c4f189918
Revises: dc4e107d5102
Create Date: 2026-06-28 17:54:22.919915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3b1c4f189918'
down_revision: Union[str, Sequence[str], None] = 'dc4e107d5102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_product_releases_product_id_version'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_product_releases_id'), 'product_releases', ['id'], unique=False)
    op.create_index(op.f('ix_product_releases_is_active'), 'product_releases', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_releases_product_id'), 'product_releases', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_releases_version'), 'product_releases', ['version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_releases_version'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_product_id'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_is_active'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_id'), table_name='product_releases')
    op.drop_table('product_releases')
    # ### end Alembic commands ###
