"""add admin reply and publish fields to feedback

Revision ID: 4c35bbfd50e0
Revises: d510685533eb
Create Date: 2026-04-06 21:15:49.083997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c35bbfd50e0'
down_revision: Union[str, Sequence[str], None] = 'd510685533eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_messages', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column(
        'feedback_messages',
        sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('feedback_messages', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_messages', 'published_at')
    op.drop_column('feedback_messages', 'is_published')
    op.drop_column('feedback_messages', 'admin_reply')
    # ### end Alembic commands ###
