"""add sale items

Revision ID: 91dfe4d46188
Revises: d8a835dfe21e
Create Date: 2026-05-15 17:51:23.119018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91dfe4d46188'
down_revision: Union[str, Sequence[str], None] = 'd8a835dfe21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_addon_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint("\n            (\n                item_type = 'product'\n                AND product_id IS NOT NULL\n                AND service_addon_id IS NULL\n            )\n            OR\n            (\n                item_type = 'service'\n                AND product_id IS NULL\n                AND service_addon_id IS NOT NULL\n            )\n            ", name='ck_sale_items_exactly_one_reference'),
    sa.CheckConstraint("item_type IN ('product', 'service')", name='ck_sale_items_item_type'),
    sa.CheckConstraint('amount >= 0', name='ck_sale_items_amount_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_addon_id'], ['service_addons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_index('ix_sale_items_sale_id_item_type', 'sale_items', ['sale_id', 'item_type'], unique=False)
    op.create_index(op.f('ix_sale_items_service_addon_id'), 'sale_items', ['service_addon_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_sale_items_service_addon_id'), table_name='sale_items')
    op.drop_index('ix_sale_items_sale_id_item_type', table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    # ### end Alembic commands ###
