"""add product_id to feedback_messages

Revision ID: c0e32fd9f9d6
Revises: e4cd21dc79fb
Create Date: 2026-04-12 19:13:27.117799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e32fd9f9d6'
down_revision: Union[str, Sequence[str], None] = 'e4cd21dc79fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_messages', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_feedback_messages_product_id'), 'feedback_messages', ['product_id'], unique=False)
    op.create_foreign_key(
        "fk_feedback_messages_product_id",
        "feedback_messages",
        "products",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback_messages', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_messages_product_id'), table_name='feedback_messages')
    op.drop_column('feedback_messages', 'product_id')
    # ### end Alembic commands ###
