"""add price and update unique constraint

Revision ID: c5103740b74b
Revises: 67372acbd380
Create Date: 2026-03-17 21:01:14.975137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5103740b74b'
down_revision: Union[str, Sequence[str], None] = '67372acbd380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_slug_edition_version', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_products_slug_version'), 'products', ['slug', 'version'])
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
