"""add consultation entitlements

Revision ID: c8093cf7f44a
Revises: 53dee3c056fc
Create Date: 2026-05-18 20:02:23.733670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8093cf7f44a'
down_revision: Union[str, Sequence[str], None] = '53dee3c056fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('booking_token', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('available', 'booked', 'expired', 'cancelled')", name='ck_consultation_entitlements_status'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_entitlements_booking_token'), 'consultation_entitlements', ['booking_token'], unique=True)
    op.create_index(op.f('ix_consultation_entitlements_sale_item_id'), 'consultation_entitlements', ['sale_item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_consultation_entitlements_sale_item_id'), table_name='consultation_entitlements')
    op.drop_index(op.f('ix_consultation_entitlements_booking_token'), table_name='consultation_entitlements')
    op.drop_table('consultation_entitlements')
    # ### end Alembic commands ###
