"""add reply sent tracking to feedback

Revision ID: cd1a2ec71b07
Revises: 4c35bbfd50e0
Create Date: 2026-04-06 22:00:03.843432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a2ec71b07'
down_revision: Union[str, Sequence[str], None] = '4c35bbfd50e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_messages', sa.Column('reply_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback_messages', sa.Column('reply_sent_to_email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_messages', 'reply_sent_to_email')
    op.drop_column('feedback_messages', 'reply_sent_at')
    # ### end Alembic commands ###
