"""add service add-ons table

Revision ID: e0418a7913dc
Revises: 091ae6472b77
Create Date: 2026-05-05 19:47:11.841021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0418a7913dc'
down_revision: Union[str, Sequence[str], None] = '091ae6472b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),

    sa.Column('family_slug', sa.String(length=100), nullable=False),
    sa.Column('package_code', sa.String(length=20), nullable=False),

    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_service_addons_amount_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_service_addons_code'), 'service_addons', ['code'], unique=True)
    op.create_index(op.f('ix_service_addons_id'), 'service_addons', ['id'], unique=False)
    op.create_index(op.f('ix_service_addons_is_active'), 'service_addons', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_addons_service_type'), 'service_addons', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_addons_family_slug'), 'service_addons', ['family_slug'], unique=False)
    op.create_index(op.f('ix_service_addons_package_code'), 'service_addons', ['package_code'], unique=False)

    op.bulk_insert(
        sa.table(
            "service_addons",
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("service_type", sa.String),
            sa.column("currency_code", sa.String),
            sa.column("amount", sa.Numeric),
            sa.column("is_active", sa.Boolean),
            sa.column("family_slug", sa.String),
            sa.column("package_code", sa.String),
        ),
        [
            {
                "code": "smartbudget_int_consultation_1h",
                "name": "1:1 Consultation",
                "service_type": "consultation",
                "family_slug": "smartbudget",
                "package_code": "INT",
                "currency_code": "EUR",
                "amount": 35.00,
                "is_active": True,
            },
            {
                "code": "smartbudget_ru_consultation_1h",
                "name": "Личная консультация",
                "service_type": "consultation",
                "family_slug": "smartbudget",
                "package_code": "RU",
                "currency_code": "RUB",
                "amount": 3500.00,
                "is_active": True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_service_addons_service_type'), table_name='service_addons')
    op.drop_index(op.f('ix_service_addons_is_active'), table_name='service_addons')
    op.drop_index(op.f('ix_service_addons_id'), table_name='service_addons')
    op.drop_index(op.f('ix_service_addons_code'), table_name='service_addons')

    op.execute("DROP INDEX IF EXISTS ix_service_addons_package_code")
    op.execute("DROP INDEX IF EXISTS ix_service_addons_family_slug")

    op.drop_table('service_addons')
    # ### end Alembic commands ###


