"""add product_prices and remove price from products

Revision ID: ee5477ce1cbd
Revises: c0e32fd9f9d6
Create Date: 2026-04-21 19:39:39.536759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5477ce1cbd'
down_revision: Union[str, Sequence[str], None] = 'c0e32fd9f9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.add_column('products', sa.Column('archive_path', sa.String(length=500), nullable=True))

    op.execute(
        """
        UPDATE products
        SET archive_path = ''
        WHERE archive_path IS NULL
        """
    )

    op.alter_column('products', 'archive_path', nullable=False)

    op.execute(
        """
        INSERT INTO product_prices (product_id, currency_code, amount, is_active)
        SELECT
            id AS product_id,
            CASE
                WHEN slug LIKE '%-ru-%' THEN 'RUB'
                ELSE 'EUR'
            END AS currency_code,
            price AS amount,
            TRUE AS is_active
        FROM products
        WHERE price IS NOT NULL
        """
    )

    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    op.drop_column('products', 'archive_path')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_table('product_prices')
    # ### end Alembic commands ###
