"""metadata sync check

Revision ID: 4816085b3919
Revises: 0b3a25b683d7
Create Date: 2026-04-05 19:24:00.114187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4816085b3919'
down_revision: Union[str, Sequence[str], None] = '0b3a25b683d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_attachments_storage_key', table_name='feedback_attachments')
    op.create_index('ix_feedback_attachments_storage_key', 'feedback_attachments', ['storage_key'], unique=False)
    op.create_unique_constraint(None, 'feedback_attachments', ['storage_key'])
    op.alter_column('feedback_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('ix_product_qna_is_published', table_name='product_qna')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_qna_is_published', 'product_qna', ['is_published'], unique=False)
    op.alter_column('feedback_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'feedback_attachments', type_='unique')
    op.drop_index('ix_feedback_attachments_storage_key', table_name='feedback_attachments')
    op.create_index('ix_feedback_attachments_storage_key', 'feedback_attachments', ['storage_key'], unique=True)
    # ### end Alembic commands ###
